# Class: zammad
class zammad (
  String $zammad_branch                               = $::zammad::params::zammad_branch,
  String $zammad_default_domain                       = $::zammad::params::zammad_default_domain,
  Stdlib::Absolutepath $zammad_default_home_directory = $::zammad::params::zammad_default_home_directory,
  Integer $zammad_default_rails_port                  = $::zammad::params::zammad_default_rails_port,
  Integer $zammad_default_websocket_port              = $::zammad::params::zammad_default_websocket_port,
  String $zammad_default_user                         = $::zammad::params::zammad_default_user,
  Integer $zammad_max_instances                       = $::zammad::params::zammad_max_instances,
  Stdlib::Absolutepath $zammad_repo_file              = $::zammad::params::zammad_repo_file,
  String $zammad_repo_key_command                     = $::zammad::params::zammad_repo_key_command,
  String $zammad_repo_template                        = $::zammad::params::zammad_repo_template,
  Optional[String] $zammad_install_options            = $::zammad::params::zammad_install_options,
  Boolean $package_manage_database                    = $::zammad::params::package_manage_database,
  Boolean $package_manage_elasticsearch               = $::zammad::params::package_manage_elasticsearch,
  Boolean $package_manage_webserver                   = $::zammad::params::package_manage_webserver,
  Boolean $package_manage_zammad                      = $::zammad::params::package_manage_zammad,
  String $package_database                            = $::zammad::params::package_database,
  String $package_elasticsearch                       = $::zammad::params::package_elasticsearch,
  String $package_webserver                           = $::zammad::params::package_webserver,
  String $package_zammad                              = $::zammad::params::package_zammad,
  String $service_database                            = $::zammad::params::service_database,
  String $service_elasticsearch                       = $::zammad::params::service_elasticsearch,
  String $service_webserver                           = $::zammad::params::service_webserver,
  String $service_zammad                              = $::zammad::params::service_zammad,
  Stdlib::Absolutepath $webserver_config              = $::zammad::params::webserver_template,
  String $webserver_template                          = $::zammad::params::webserver_template,
  Stdlib::Httpurl $es_url                             = $::zammad::params::es_url,
  Integer $es_port                                    = $::zammad::params::es_port,
  String $es_plugin_install_command                   = $::zammad::params::es_plugin_install_command,
  String $es_url_config_command                       = $::zammad::params::es_url_config_command,
  String $es_index_create_command                     = $::zammad::params::es_index_create_command,
  String $es_version                                  = $::zammad::params::es_version,
  String $es_repo_key_command                         = $::zammad::params::es_repo_key_command,
  Stdlib::Absolutepath $es_repo_file                  = $::zammad::params::es_repo_file,
  String $es_repo_template                            = $::zammad::params::es_repo_template,
) inherits ::zammad::params {

  include ::zammad::install
  include ::zammad::service
}
